### ISSUE TITLE
Steve Carts Reborn and Lag B Gone do not play nice

### ISSUE THREAD

**Issue by Magesw** [DoctorFTB/LagBGonReborn#1]
I am using FTB Sky Adventures pack that has Steve Carts Reborn in it and I added Lag B Gone to the server to control lag.

One of my players complained that Lag B Gone ate his cart, so I crafted a new one for him we put it down I scanned entities for its ID added it to the list and next go around it ate it again. So I held it in my hand added it to entity list it gave a completely different name so I added that name plus the name that the scan entities command gave to the list and it ate it next go around yet again.

Not sure what to put in to make Lag B Gone not eat Steve Carts carts.

Server version 1.12.2
Lag B Gone version: 1.0.0
Steve Carts version: 2.4.24.118

**Comment by DoctorFTB** [comment]
Hi.
After tests with Steve Carts - I look only "stevescarts:cart.0".
Try "/bgon toggleentity stevescarts:cart.0".

**Comment by Magesw** [comment]
I do have that one added already and lag b gone still ate the cart.

**Comment by DoctorFTB** [comment]
Its weird.
After I add this in blacklist - my test carts not deleted.
I want add modid:* support.
I think update fix this issue.

**Comment by Magesw** [comment]
Well I tried again and it seems to be fine, was weird I had added that like you gave before and it ate it. Maybe a typo? I dunno. Thanks!
