### ISSUE TITLE
Massive randomly chunk generating

### ISSUE THREAD

**Issue by Unse** [DoctorFTB/LagBGonReborn#4]
Hello.
I've added LagBGon Reborn 1.0.2 to FTB Revelation 1.12.2 (ver 2.6.0) modpack.
All was good and well, but after a while, about 2 days ago, server started lagging so much that it had to skip ticks.
After some inspection we found out that server was generating EXTREMELY high amount of random chunks (thanks, Dynmap!).
There were no hints in console (even with WorldGeneration-Profiler) on who's fault is it. So I had to disable mods one by one to find the culprit. And, eventually, with disabling, enabling, and disabling again, I've came to conclusion that the issue lies with LagBGon. You can see [the map with an example](https://mc.unserver.ru/dynmap/). All the red squared area is world border and pregenerated chunks. Everything outside red square - generated (presumably) by LagBGon.
Can you, please, look into this issue?

Steps to reproduce:
1. Install FTB Revelation 1.12.2 (ver 2.6.0) modpack
2. Install LagBGon Reborn
3. Add Dynmap
4. Run server, wait a while (couple of days maybe)
5. (Not sure) Try to load couple of chunks (fast move through unloaded chunks) for activate LagBGon chunk unloading procedure.
6. Eventually it begins generating chunks randomly... ( this can be tracked by .mca region files on server )

It may not be LagBGon Reborn's fault in the end, but removing it solved the issue, so...

**Comment by DoctorFTB** [comment]
Hi. Rus? O_
I check code.
Code work only with loaded chucks.
Code not generate new chunks..

**Comment by Unse** [comment]
Yes. _O
As i  say - It may not be LagBGon fault in the end, but removing it solved the issue.

**Comment by DoctorFTB** [comment]
Join to discord & go DM.

**Comment by DoctorFTB** [comment]
@Unse

**Comment by DoctorFTB** [comment]
shrug

**Comment by thiakil** [comment]
https://github.com/DoctorFTB/LagBGonReborn/blob/362f0cb8892b07524423d98f1f7ea7d082191c61/src/main/java/ftblag/lagbgonreborn/LBGEvents.java#L24

`getChunk` expects a chunk position, you're giving it a block position.
