### ISSUE TITLE
ATM 3 Remix Server Crashing

### ISSUE THREAD

**Issue by Beserkerlel** [DoctorFTB/LagBGonReborn#5]
https://pastebin.com/qMCK2bVS

I run a ATM 3 Remix server and whenever we have your mod installed we get a crash report identical to this fairly frequently. We've disabled the mod for several days at a time and had no similar crashes while it is off. I've checked with the All The Mods discord and a couple other network owners have had the same issue with their servers that also have this mod installed. 

I dug into every full log (20+ crashes) related to a crash with the same cause and every crash happens 10 seconds to 180 seconds at max after lagbgon unloads chunks. Was hoping we could get you to look into it. Can provide any further information you need.

**Comment by Halfdeaf** [comment]
I am seeing the same thing across 4 servers.

**Comment by DoctorFTB** [comment]
Hmm.. Its weird..
I not found any mistake by mod.
Player break leaves.
MC code get state from block.
MC code search property "PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockPlanks$EnumType, values=[oak, spruce, birch, jungle]}"
But stage not have "oak / spruce / birch / jungle" because block is Air -> "BlockStateContainer{block=minecraft:air, properties=[]}"

**Comment by Halfdeaf** [comment]
It's not even a player breaking leaves. This happens when exploring and always less than 90 seconds after Lagbgon unloads chunks. I have a few reports that have a different block instead of air namely Mossy Cobble, stone and water

**Comment by DoctorFTB** [comment]
About leaves -> I get info from crash.

**Comment by Halfdeaf** [comment]
I'm also getting Integrated Dynamics complaining in the logs after lagbgon unloads https://pastebin.com/hJWBRV9c

**Comment by Beserkerlel** [comment]
Is it possible that the unloading is happening during/before a leaf decay event and due to lag the unloading happens before the decay, causing the server look for a block to decay when there is none loaded?

**Comment by P3rf3ctXZer0** [comment]
Maybe add a check to ignore unloaded entities.

**Comment by DoctorFTB** [comment]
After 1 month testing by @ Halfdeaf I think I fix bug.. Fix in public.
Need tests.
1.0.5 version.

**Comment by DoctorFTB** [comment]
Closed. In code: fixed. Not tested because TS not send any answer.
