### ISSUE TITLE
Extra Utils 2 Flat nodes get wiped even if in the blacklist

### ISSUE THREAD

**Issue by jinkhya** [DoctorFTB/LagBGonReborn#6]
Hello,

Title says it all. :)
in config (I removed the other items that work fine) : 

S:ItemBlackList <
extrautils2:flattransfernode
>

**Comment by DoctorFTB** [comment]
extrautils2:flattransfernode is Entity, not item.

**Comment by DoctorFTB** [comment]
@jinkhya
